// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAePOqwbZYBCEuLcGgGPRzcE49McLNn40E',
    appId: '1:410431487573:web:794ac79ae11862ddeb1edc',
    messagingSenderId: '410431487573',
    projectId: 'hhf-social',
    authDomain: 'hhf-social.firebaseapp.com',
    storageBucket: 'hhf-social.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYkIz2CytbLbP6GcEGnpFhXFeLKN2Kn-I',
    appId: '1:410431487573:android:04be876bebb08c69eb1edc',
    messagingSenderId: '410431487573',
    projectId: 'hhf-social',
    storageBucket: 'hhf-social.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiq5q2WrSDXLMVyZhUc48pofeHlrmDVv0',
    appId: '1:410431487573:ios:d0e1e010b89fccfeeb1edc',
    messagingSenderId: '410431487573',
    projectId: 'hhf-social',
    storageBucket: 'hhf-social.firebasestorage.app',
    iosBundleId: 'com.hhfmediagrp.hhfsocial',
  );
}
